package com.md5.viewer.selector.gui;


import java.awt.event.MouseAdapter;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Tim Poliquin
 */
public class AnimationSelectorGUI extends javax.swing.JFrame {

    // Variables declaration - do not modify
    private JButton btnAdd;
    private JButton btnBaseAnimLoad;
    private JButton btnHierarchyLoad;
    private JButton btnRemove;
    private JButton btnOK;
    private JButton btnCancel;
    private JScrollPane jScrollPane1;
    private JLabel lblAnimations;
    private JLabel lblBaseAnimation;
    private JLabel lblBodyHierarchy;
    private JList lstAnimations;
    private JTextField txtBaseAnimation;
    private JTextField txtHierarchyFile;
    private MD5MouseAdapter mouseAdapter;
    
    /** Creates new form MD5Viewer */
    public AnimationSelectorGUI() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AnimationSelectorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AnimationSelectorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AnimationSelectorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AnimationSelectorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents() {
    	this.setResizable(false);
    	this.mouseAdapter = new MD5MouseAdapter();
        jScrollPane1 = new JScrollPane();
        lstAnimations = new JList();
        lblBodyHierarchy = new JLabel();
        txtHierarchyFile = new JTextField();
        btnHierarchyLoad = new JButton();
        lblBaseAnimation = new JLabel();
        txtBaseAnimation = new JTextField();
        btnBaseAnimLoad = new JButton();
        btnAdd = new JButton();
        lblAnimations = new JLabel();
        btnRemove = new JButton();
        btnOK = new JButton();
        btnCancel = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstAnimations.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lstAnimations.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAnimations);

        lblBodyHierarchy.setLabelFor(txtHierarchyFile);
        lblBodyHierarchy.setText("Model Hierarchy");

        txtHierarchyFile.setEditable(false);
        txtHierarchyFile.setText("<Select A File>");

        btnHierarchyLoad.setText("Open");
        btnHierarchyLoad.setToolTipText("Select a Model Hierarchy File");
        btnHierarchyLoad.setName("btnHierarchyLoad");
        btnHierarchyLoad.addMouseListener(this.mouseAdapter);

        lblBaseAnimation.setText("Base Animation");

        txtBaseAnimation.setEditable(false);
        txtBaseAnimation.setText("<Select A File>");

        btnBaseAnimLoad.setText("Open");
        btnBaseAnimLoad.setToolTipText("Select a base animation file");
        btnBaseAnimLoad.setName("btnBaseAnimLoad");
        btnBaseAnimLoad.addMouseListener(this.mouseAdapter);

        btnAdd.setText("Add");
        btnAdd.setToolTipText("Add an animation for playback");
        btnAdd.setName("btnAdd");
        btnAdd.addMouseListener(this.mouseAdapter);

        lblAnimations.setText("Animations");

        btnRemove.setText("Remove");
        btnRemove.setToolTipText("Remove the selected animation");
        btnRemove.setName("btnRemove");
        btnRemove.addMouseListener(this.mouseAdapter);

        btnOK.setText("OK");
        btnOK.setToolTipText("Enter the MD5 Viewer");
        btnOK.setName("btnOK");
        btnOK.addMouseListener(this.mouseAdapter);

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Exit the application");
        btnCancel.setName("btnCancel");
        btnCancel.addMouseListener(this.mouseAdapter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBodyHierarchy)
                    .addComponent(lblBaseAnimation)
                    .addComponent(lblAnimations)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHierarchyFile, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txtBaseAnimation, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemove)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(btnBaseAnimLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(btnHierarchyLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnOK, btnCancel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnBaseAnimLoad, btnHierarchyLoad, btnRemove});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, txtBaseAnimation, txtHierarchyFile});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBodyHierarchy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHierarchyFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHierarchyLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBaseAnimation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBaseAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaseAnimLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnimations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

}
